<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
        $this->load->model('Member_model');
    }
    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			if($this->session->userdata('username') == 'admin'){
				$this->load->view('Home');
			}
			else{
				$this->load->view('Home_member');
			}	
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Login');
		}
		else
		{
			$username=$this->input->post('username'); //username=name form
			$password=$this->input->post('password');
			
			$cek_login=$this->Admin_model->cek_login($username,$password);
			$cek_login_member=$this->Member_model->cek_login_member($username,$password);


			if(!empty($cek_login)){
				$this->session->set_userdata('logined',true);
				$this->session->set_userdata('username',$username);
				$this->session->set_userdata('username',$cek_login->username);
				$this->load->view('admin/Home');
			}

			else if(!empty($cek_login_member)){
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username',$username);
				$this->session->set_userdata('id_member',$cek_login_member->id_member);
				$this->load->view('Home_member');
			}

			else 
			{
				$this->session->set_flashdata('gagal','Gagal Login');	
				echo "gagal";
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('username');

		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */
